signs:
  Guardian: GuardianSign,takePlayerMoney
messages:
  setup:
    Guardian: You have created a Guardian sign that costs !price to buy !guardians Guardian(s)!
  confirm:
    Guardian: Pay !price for !guardians Guardian(s)? You have !currentguardians Guardian(s).
  transaction:
    Guardian: You paid !price for !guardians additional Guardian(s)! You now have !currentguardians Guardian(s).
  transaction_owner:
    Guardian: \!customer paid !price for !guardians additional Guardian(s)!
errors:
  player_has_guardians_left: You have !guardians Guardian(s) left!
  player_used_last_guardian: You just used your last Guardian, make sure you stock up soon!
  player_has_no_guardian: You don't have any more Guardian, your lost inventory will not be saved for you.