# SignShopGuardian can be enabled per world, it is enabled in all worlds by default.
# An example of how to only enable SignShopGuardian for the world LOL (and disable it for all other worlds):
# EnabledWorlds:
#   - LOL

signs:
  Guardian: givePlayerGuardians,takePlayerMoney,playerIsOp
  GuardianXP: givePlayerGuardians,takePlayerXP,playerIsOp
messages:
  setup:
    Guardian: You have created a Guardian sign that costs !price to buy !guardians Guardian(s)!
    GuardianXP: You have created a Guardian sign that costs !xp levels to buy !guardians Guardian(s)!
  confirm:
    Guardian: Pay !price for !guardians Guardian(s)? You have !currentguardians Guardian(s).
    GuardianXP: Pay !xp levels for !guardians Guardian(s)? You have !currentguardians Guardian(s).
  transaction:
    Guardian: You paid !price for !guardians additional Guardian(s)! You now have !currentguardians Guardian(s).
    GuardianXP: You paid !xp levels for !guardians additional Guardian(s)! You now have !currentguardians Guardian(s).
  transaction_owner:
    Guardian: ''
    GuardianXP: ''
errors:
  player_has_guardians_left: You have !guardians Guardian(s) left!
  player_used_last_guardian: You just used your last Guardian, make sure you stock up soon!
  player_has_no_guardian: You don't have any more Guardians, your inventory was not saved!
  player_has_insufficient_guardians: You don't have any guardians left to sell! (You need at least !guardians)
  guardian_not_allowed_in_world: Guardians are not allowed in this world.